<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>TIKSN.Lionize.HabiticaTaskProviderService.Business</RootNamespace>
    <AssemblyName>TIKSN.Lionize.HabiticaTaskProviderService.Business</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Bond.CSharp" Version="10.0.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="8.0.0" />
    <PackageReference Include="TIKSN-Framework" Version="4.5.1" />
    <PackageReference Include="TIKSN-Habitica" Version="1.0.2" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="TIKSN.Lionize.Messaging" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
  </ItemGroup>

</Project>
